### ISSUE TITLE
janitor for development?

### ISSUE THREAD

**Issue by samrocketman** [gimp-ci/docker-jenkins-gimp#4]
Mentioned on IRC and might be worth checking out.

```
03:10 < buovjaga> samrocketman: do you know about https://janitor.technology/ ? It still needs a lot of work, but seems your setup would make it easy to transport there
03:11 < buovjaga> here is like a quickstart: https://discourse.janitor.technology/t/how-to-add-a-project/165
03:16 < samrocketman> I've not seen janitor before.
03:16 < samrocketman> Interesting, probably would not be a huge level of effort to add to it.
03:17 < samrocketman> Not sure if janitor would be a good fit for GIMP, though.
03:17 < samrocketman> Part of the development process is a need to launch the X11 GUI and play with it (I imagine without actually being a developer).
03:17 < samrocketman> Seems janitor and cloud9 are good for web apps, though.
03:21 < buovjaga> samrocketman: it is an effort by Mozilla folks
03:22 < buovjaga> samrocketman: it works for desktop apps, such as GIMP
03:23 < samrocketman> Ah, that was not obvious to me.
03:24 < buovjaga> the most recent demo: https://www.youtube.com/watch?v=jHomOSa_WEc
03:24 < samrocketman> I'll create a GitHub so I don't forget about it.
```

**Comment by schumaml** [comment]
What's the non-marketing (aka technical) summary for what janitor does?

**Comment by samrocketman** [comment]
I'm not sure, at some point might be worth investigating so I created this issue so I don't forget about it.

At the moment, my primary focus is on the Jenkins re-architecture.

**Comment by samrocketman** [comment]
# DEPRECATED

This project has been migrated to [GNOME GitLab under World/gimp-ci](https://gitlab.gnome.org/World/gimp-ci).  Refer to [the documentation repository for better information](https://gitlab.gnome.org/World/gimp-ci/documentation).  If you just want to build GIMP, then [check out the GIMP development environment based on Docker](https://gitlab.gnome.org/World/gimp-ci/docker-gimp).  The Docker environment also allows you to run GIMP if you have Xorg display; instructions therein.
